---
title: "Advantage of two scans in small populations demonstrated with a transgender dataset."
author: "Freya Acar"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Introduction

# Actual data
```{r ReadData, include = FALSE}

```
## Descriptives
### About the population
### Variables of interest

## Analysis of 1 measurement

## Analysis of the average

## Analysis of 2 measurements

# Simulations
## Intro

## Code
```{r Simulations setup, echo = FALSE, warning = FALSE, include = FALSE}
  # Working directory
```
First we need to define the parameters of our simulations. 
```{r Simulations parameters}
  # Number of simulations
  nsim <- 10

  # number of participants in case of 1 measure per participants
  n.1 <- c(20,30,50)
  
  # number of participants in case of 2 measures per participants
  n.2 <- c(10, 20, 30, 40, 50, 60, 70, 80, 90, 100)

  # Variance on population level
  var <- 1
  
  # Effect in group 1, equal to 0
  mean <- 0
  
  # Difference between groups
  # This is similar to the difference between groups in our dataset
  delta <- c(0.25, 0.5, 1)

  # Obtain an average correlation of 0.82 between 2 measures of the same participant
  alph <- c(0.6, 0.7, 0.8, 0.9)
  
  # Significance level
  sig <- 0.05
```

```{r Simulations code}
  # Libraries
  library(lme4)

  # Construct arrays to save data
  power.1 <- array(data=NA, dim = c(nsim, length(n.1), length(n.2), length(delta), length(alph)))
  power.2 <- array(data=NA, dim = c(nsim, length(n.1), length(n.2), length(delta), length(alph)))
  p.1 <- array(data=NA, dim = c(length(n.1), length(n.2), length(delta), length(alph)))
  p.2 <- array(data=NA, dim = c(length(n.1), length(n.2), length(delta), length(alph)))
  
  for(n1 in 1:length(n.1)){
    for(n2 in 1:length(n.2)){
      for(d in 1:length(delta)){
        for(a in 1:length(alph)){
          for(i in 1:nsim){
            # Simulate data
              # 1 measure per participant
              X1.1 <- rnorm(n = n.1[n1], mean = mean, sd = sqrt(var))
              X2.1 <- rnorm(n = n.1[n1], mean = delta[d], sd = sqrt(var))
              X.1 <- c(X1.1, X2.1)
              Y.1 <- c(rep(0, n.1[n1]), rep(1, n.1[n1]))
              
              # 2 measures per participant
              X1.2f <- rnorm(n = n.2[n2], mean = mean, sd = sqrt(var))
              X1.2s <- alph[a]*X1.2f + rnorm(n = n.2[n2], mean = 0, sd = sqrt(var))
              X2.2f <- rnorm(n = n.2[n2], mean = delta[d], sd = sqrt(var))
              X2.2s <- alph[a]*X2.2f + rnorm(n = n.2[n2], mean = 0, sd = sqrt(var))
              X.2 <- c(X1.2f, X1.2s, X2.2f, X2.2s)
              Y.2 <- c(rep(0, n.2[n2]*2), rep(1, n.2[n2]*2))
              subject <- rep(1:n.2[n2],4)
              
            # Compute power
              # 1 measure per participant: GLM with group as predictor
              GLM.1 <- glm(X.1 ~ Y.1)
              # 1 measure per participant: compute power
              power.1[i,n1,n2,d,a] <- as.numeric(unlist(summary(GLM.1)[12])[8])
              
              # 2 measures per participant: mixed model with random intercept and group as predictor
              MM.2 <- lmer(X.2 ~ Y.2 + (1 | subject))
              power.2[i,n1,n2,d,a] <- as.numeric(unlist(summary(MM.2)[10])[6])
          }
            tcut <- qt(p = sig, df = (n.2[n2]*4)-2)
            p.1[n1,n2,d,a] <- as.numeric(unlist(table(power.1[,n1,n2,d,a] < sig))[2])/nsim
            p.2[n1,n2,d,a] <- as.numeric(unlist(table(power.2[,n1,n2,d,a] > tcut))[2])/nsim
    }}}}
```


## Results
```{r Simulation results}
p.1[1,1,1,1]
```

# Discussion

```{r temp, echo=FALSE}
temp <- 1
```
